name: Playwright Tests
on:
  push:
    branches: [ "team5Bootcam" ]
  pull_request:
    branches: [ "team5Bootcam" ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & Install
      run: dotnet build
    - name: Install Playwright
      run: dotnet tool restore && dotnet playwright install
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      run: dotnet test
