# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "team5Bootcam" ]
  pull_request:
    branches: [ "team5Bootcam" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' 

      # Install dependencies Playwright
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxrandr2 libxkbcommon0 libxcomposite1 libxdamage1 libxshmfence1 libgbm1

      # Restore NuGet dependencies
      - name: Restore NuGet packages
        run: dotnet restore

      # Compile project
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Install Playwright browsers
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
        env:
          DOTNET_ROOT: /home/runner/.dotnet
      - name: Install Playwright browsers
        run: playwright install
        env:
          DOTNET_ROOT: /home/runner/.dotnet

      # Executing the tests
      - name: Run Playwright tests
        run: dotnet test --configuration Release --no-build
