# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "team5Bootcam" ]
  pull_request:
    branches: [ "team5Bootcam" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PlaywrightDemo.sln
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Build
      run: dotnet build PlaywrightDemo.sln --no-restore
    - name: Test
      run: dotnet test PlaywrightDemo.sln --no-build --verbosity normal
